module.exports = {
  disallowAttributeConcatenation: true,
  disallowAttributeInterpolation: true,
  disallowAttributeTemplateString: null,
  disallowBlockExpansion: null,
  disallowClassAttributeWithStaticValue: true,
  disallowClassLiteralsBeforeAttributes: null,
  disallowClassLiteralsBeforeIdLiterals: true,
  disallowClassLiterals: null,
  disallowDuplicateAttributes: true,
  disallowHtmlText: true,
  disallowIdAttributeWithStaticValue: true,
  disallowIdLiteralsBeforeAttributes: null,
  disallowIdLiterals: null,
  disallowLegacyMixinCall: true,
  disallowMultipleLineBreaks: true,
  disallowSpaceAfterCodeOperator: null,
  disallowSpacesInsideAttributeBrackets: true,
  disallowSpecificAttributes: [
    {
      a: 'name',
      caption: ['align'],
      img: ['align', 'border', 'hspace', 'vspace'],
      table: ['align', 'bgcolor', 'height'],
      tr: ['bgcolor'],
      td: ['bgcolor', 'nowrap', 'width'],
      th: ['bgcolor', 'nowrap', 'width'],
      hr: ['align', 'noshade', 'size', 'width'],
      div: ['align'],
      h1: ['align'],
      h2: ['align'],
      h3: ['align'],
      h4: ['align'],
      h5: ['align'],
      h6: ['align'],
      p: ['align'],
      body: ['alink', 'background', 'bgcolor', 'link', 'text', 'vlink'],
      object: ['border', 'hspace', 'vspace'],
      br: ['clear'],
      ul: ['compact'],
      ol: ['compact', 'start'],
      li: ['type', 'value'],
      script: ['language'],
      basefont: ['size'],
      font: ['size'],
      pre: ['width'],
    },
  ],
  disallowSpecificTags: [
    'acronym',
    'applet',
    'basefont',
    'big',
    'blink',
    'center',
    'dir',
    'embed',
    'font',
    'frame',
    'frameset',
    'image',
    'isindex',
    'listing',
    'marquee',
    'menu',
    'menuitem',
    'nobr',
    'noembed',
    'noframes',
    'param',
    'plaintext',
    'rb',
    'rtc',
    's',
    'strike',
    'tt',
    'u',
    'xmp',
  ],
  disallowStringConcatenation: true,
  disallowStringInterpolation: true,
  disallowTagInterpolation: null,
  disallowTemplateString: null,
  disallowTrailingSpaces: true,
  maximumLineLength: null,
  maximumNumberOfLines: null,
  requireClassLiteralsBeforeAttributes: true,
  requireClassLiteralsBeforeIdLiterals: null,
  requireIdLiteralsBeforeAttributes: true,
  requireLineFeedAtFileEnd: true,
  requireLowerCaseAttributes: true,
  requireLowerCaseTags: true,
  requireSpaceAfterCodeOperator: true,
  requireSpacesInsideAttributeBrackets: null,
  requireSpecificAttributes: [
    {
      form: 'action',
    },
    {
      img: 'alt',
    },
    {
      input: 'type',
    },
    {
      'input[type=submit]': 'value',
    },
  ],
  requireStrictEqualityOperators: true,
  validateAttributeQuoteMarks: "'",
  validateAttributeSeparator: {
    separator: ', ',
    multiLineSeparator: ',\n  ',
  },
  validateDivTags: true,
  validateExtensions: true,
  validateIndentation: 2,
  validateLineBreaks: 'LF',
  validateSelfClosingTags: true,
  validateTemplateString: true,
};
